title: Anova's Portfolio
description: Welcome to my portfolio website! My name is Anova Sarkar. I am currently in my fifth year of City College, majoring in Computer Science. A fun fact about myself is that I like to draw digitally in my spare time! My go to program for digital art is Sketchbook.
remote_theme: pages-themes/cayman@v0.2.0
