title: Anova's Portfolio
description: Welcome to my portfolio website! My name is Anova Sarkar. I am currently in my fifth year of City College, majoring in Computer Science.
remote_theme: pages-themes/cayman@v0.2.0
